# DataSource Config
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:${user.dir}/db/test
    username: root
    password: 123456
  sql:
    init:
      schema-locations: ./sql/db/schema-h2.sql
      data-locations: ./sql/db/data-h2.sql
      mode: always
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
camunda:
  bpm:
    admin-user:
      id: admin
      password: 123456
    filter:
      create: All tasks
